DROP TABLE IF EXISTS `ADMIN_USER_TABLE`;
CREATE TABLE `ADMIN_USER_TABLE` (
	`ADMIN_ID` CHAR(20) NOT NULL,
	`ADMIN_PW` CHAR(20) NOT NULL,
	`ADMIN_NAME` CHAR(10) NOT NULL,
	`ADMIN_GENDER` ENUM('남자','여자') NOT NULL,
	`ADMIN_PHONENUMBER` CHAR(13) NOT NULL,
	`ADMIN_EMAIL` CHAR(40) NOT NULL,
	PRIMARY KEY(`ADMIN_ID`)
)
